//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string book_name { get; set; }
        public int page_count { get; set; }
        public System.DateTime reading_date { get; set; }
        public string autor { get; set; }
    
        public virtual users users { get; set; }
    }
}
